//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verification.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0 | СЕРЬЕЗНОСТЬ | ОШИБКА |   |   | ЭТАП ПРОВЕРКИ |
        ///1 | Warning | Имя начинается с маленькой буквы |  |  | Лексический |
        ///2 | Warning | Первое слово возможно не является именем существительным |   |   | Лексический |
        ///3 | Warning | Нет знака вопроса |   |   | Лексический |
        ///4 | Serious | Отсутствует подпись условия |   |   | Лексический |
        ///5 | Serious | Неподписанная альтернатива |   |   | Лексический |
        ///6 | Serious | Переход имеет подпись, не являясь условием или альтернативой |   |   | Лексический |
        ///7 |  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ADMistakes {
            get {
                return ResourceManager.GetString("ADMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\pard\sa180\fs24 О программе\par}
        ///{\pard Данная программа предназначена для верификации UML диаграммы активностей (ДА), классов (ДК) и прецедентов (ДП). \par}
        ///.
        /// </summary>
        internal static string HelpGeneral {
            get {
                return ResourceManager.GetString("HelpGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\pard\sa180\fs24 Работа с программой\par}
        ///{\pard\b Добавление модели \b0\par}
        ///{\pard Для добавления новой модели нажмите на кнопку &quot;Добавить&quot; и выберите необходимые файлы. Одновременно возможно добавлять любое количество моделей. \par}
        ///{\pard Для установления связи между XMI файлом и PNG изображением необходимо, чтобы имена файлов были одинаковыми. \par}
        ///.
        /// </summary>
        internal static string HelpProgram {
            get {
                return ResourceManager.GetString("HelpProgram", resourceCulture);
            }
        }
    }
}
